version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image:  mariadb:10.11.2
    restart: always
    environment:
      MARIADB_USER: root
      MARIADB_DATABASE: database
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    # networks:
    #     - net-app

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
